## List Comprehension Method


In [135]:
squared = [i**2 for i in range(10) if i % 2 == 0]
print(squared)

[0, 4, 16, 36, 64]


In [137]:
marks = []
marks.append(10)
print(marks)

[10]


In [ ]:
squared = [i**2 for i in range(10) if i % 2 == 0]
print(squared)
first = []
for i in range(0, 3):
    first.append(squared[i])
print(first)

[0, 4, 16, 36, 64]
[0, 4, 16]


### List Slicing


In [ ]:
squared = [i**2 for i in range(100)]
print(squared)
first = squared[2:5:2]
print(first)
odd = squared[:5:3]
print(odd)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676, 729, 784, 841, 900, 961, 1024, 1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849, 1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916, 3025, 3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225, 4356, 4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776, 5929, 6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569, 7744, 7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604, 9801]
[4, 16]
[0, 9]


In [ ]:
##List Reverse

squared = [i**2 for i in range(10)]
squared = squared[7:2:-1]
print(squared)

[49, 36, 25, 16, 9]


### List Copy


In [141]:
lst1 = [10, 20, 30, "AI", "Vacation"]
print(lst1)
lst2 = lst1
print(lst2)
lst2.append(200)
print(lst2)
print(lst1)

[10, 20, 30, 'AI', 'Vacation']
[10, 20, 30, 'AI', 'Vacation']
[10, 20, 30, 'AI', 'Vacation', 200]
[10, 20, 30, 'AI', 'Vacation', 200]


In [142]:
lst3 = lst1.copy()
lst3.pop()
print(lst1)
print(lst2)
print(lst3)

[10, 20, 30, 'AI', 'Vacation', 200]
[10, 20, 30, 'AI', 'Vacation', 200]
[10, 20, 30, 'AI', 'Vacation']


In [143]:
# mutable - list, string, dictionary
# imutable - int, float, tuple

a = "AI Lav at very"
print(a)
print(a + "b")
a = a.replace("Lav", "Lab")
print(a)
print(a.index("b"))

AI Lav at very
AI Lav at veryb
AI Lab at very
5


In [144]:
lst1.append([20, 30, 40])
print(lst1)
lst2 = lst1.copy()  ###shallow copy
print(lst2)
# lst2.remove(20)
# print(lst1,lst2)


print(lst2[-1][0])
lst2[-1].pop()
print(lst2)
print(lst1)

[10, 20, 30, 'AI', 'Vacation', 200, [20, 30, 40]]
[10, 20, 30, 'AI', 'Vacation', 200, [20, 30, 40]]
20
[10, 20, 30, 'AI', 'Vacation', 200, [20, 30]]
[10, 20, 30, 'AI', 'Vacation', 200, [20, 30]]


In [145]:
## DEEP COPY

import copy

lst3 = copy.deepcopy(lst1)
print(lst3)
lst2[-1].pop()
lst3[-1].pop(1)
print(lst1)
print(lst2)
print(lst3)

[10, 20, 30, 'AI', 'Vacation', 200, [20, 30]]
[10, 20, 30, 'AI', 'Vacation', 200, [20]]
[10, 20, 30, 'AI', 'Vacation', 200, [20]]
[10, 20, 30, 'AI', 'Vacation', 200, [20]]


## Tuple


In [ ]:
a = (1, 2, 3, 4, 65)
print(type(a))
print(a[0])
temp = (32, 34, 5, 63, 2, 37)
print(temp)
coordinate = (0, 0)
adjacency_list = [("A", 5), ("B", 6), ("C", 4)]
print(adjacency_list[1][1])

<class 'tuple'>
1
(32, 34, 5, 63, 2, 37)
6


## Dictionary


In [ ]:
# course={}

s = "Our class will be held online today"
course = {
    "code": "CSE 3812",  # left side er gulo holo keys, and right side er gulo holo values
    "name": "AI Lab",
    "credit hour": 1,
    "duration": 2.5,
    "grades": ["A", "A-", "C"],
    827: "Room Number",
    3.5: "Avg",
}
print(type(course))
print(course)

<class 'dict'>
{'code': 'CSE 3812', 'name': 'AI Lab', 'credit hour': 1, 'duration': 2.5, 'grades': ['A', 'A-', 'C'], 827: 'Room Number', 3.5: 'Avg'}


### Indexing


In [ ]:
print(course["code"])
print(course.get("name"))

CSE 3812
AI Lab


### Iteration


In [ ]:
course.values()
course.keys()
course.items()

dict_keys(['code', 'name', 'credit hour', 'duration', 'grades', 827, 3.5, 'room'])

In [ ]:
for i in course.keys():
    print(i, course[i])

code CSE 3812
name AI Lab
credit hour 1
duration 2.5
grades ['A', 'A-', 'C']
827 Room Number
3.5 Avg


In [ ]:
course["room"] = 727
course

{'code': 'CSE 3812',
 'name': 'AI Lab',
 'credit hour': 1,
 'duration': 2.5,
 'grades': ['A', 'A-', 'C'],
 827: 'Room Number',
 3.5: 'Avg',
 'room': 727}

## Numpy Library


In [ ]:
lst1 = [1, 2, 3]
lst2 = [4, 5, 6]
print(lst1 + lst2)
print(lst1 * 3)

[1, 2, 3, 4, 5, 6]
[1, 2, 3, 1, 2, 3, 1, 2, 3]


In [ ]:
import numpy as np

arr1 = np.array(lst1)
print(type(arr1))
arr2 = np.array(lst2)
print(type(arr2))
print(arr1 + arr2)
print(arr1 * 3)
print(arr1.shape)

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
[5 7 9]
[3 6 9]
(3,)


In [ ]:
arr = np.ones((3,), "int64")  # int64 comma remove kore
print(arr)
arr = np.ones((3, 4), "int64")  # int64 comma remove kore
print(arr)
arr = np.zeros((3, 3), "int64")
print(arr)

[1 1 1]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
arr2 = np.arange(40)
print(arr2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]


In [ ]:
arr2 = np.arange(40, step=2, dtype="float32")  # float dewar karon e dosomik show korche
print(arr2)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38]


In [ ]:
arr2 = np.arange(0, 1, step=0.01, dtype="float32")
print(arr2)

[0.         0.01       0.02       0.03       0.04       0.05
 0.06       0.07       0.08       0.09       0.09999999 0.11
 0.12       0.13       0.14       0.14999999 0.16       0.17
 0.17999999 0.19       0.19999999 0.21       0.22       0.22999999
 0.24       0.25       0.26       0.26999998 0.28       0.29
 0.29999998 0.31       0.32       0.32999998 0.34       0.35
 0.35999998 0.37       0.38       0.39       0.39999998 0.41
 0.42       0.42999998 0.44       0.45       0.45999998 0.47
 0.48       0.48999998 0.5        0.51       0.52       0.53
 0.53999996 0.55       0.56       0.57       0.58       0.59
 0.59999996 0.61       0.62       0.63       0.64       0.65
 0.65999997 0.66999996 0.68       0.69       0.7        0.71
 0.71999997 0.72999996 0.74       0.75       0.76       0.77
 0.78       0.78999996 0.79999995 0.81       0.82       0.83
 0.84       0.84999996 0.85999995 0.87       0.88       0.89
 0.9        0.90999997 0.91999996 0.93       0.94       0.95
 0.96       0.9699

In [ ]:
arr2 = np.linspace(0, 1, 10)  # 10 mane 10 vag e vag korche
print(arr2)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [152]:
arr = np.random.rand(2, 2)  # rand generates float numbers
print(arr)
arr = np.random.randint(0, 10, 6)  # randint integer number generate kore
print(arr)

[[0.64041742 0.34409309]
 [0.75755854 0.75425066]]
[6 4 9 6 1 1]
