# Intro to Python

In [ ]:
print('Hello world')

## Variables

In [ ]:
a = 5
print(type(a)) # strongly-typed
print(a)
# a = 'Lab'
# Typecasting
a = str(a) + 'AI'
print(type(a))
print(a)

In [ ]:
a = 5.0
# a = int(a)
# a = str(a) + 'AI'
a = a + 2
print(a)

## Operators

In [ ]:
a = 10
a = a + 5 # 15
print(a)
a = a - 2 # 13
print(a)
a = a * 3 # 39
print(a)
a = a / 2 # truediv, 19.5
print(a)
a = a // 2 # intdiv, 9.0
print(a)
a = a % 3
print(a)
a = a ** 2
print(a)
print('Value of a is '+str(a))

In [ ]:
course = 'AI Lab'
classroom = 827
print(f'The course is {course} and it is held in room {classroom}')

## If-else

In [ ]:
x = 2
if x % 2 != 0:
  print('Even')
  x += 2
else:
  print('Odd')

print(x)

In [ ]:
marks = 86
if marks >= 90:
  print('A')
elif marks >= 86:
  print('A-')
else:
  print('F')

## User Input

In [ ]:
n = float(input('Enter a number'))
print(n)
print(type(n))

x = 10 + n
print(x)

## Loops

In [ ]:
for i in range(2,11,2):
  if i % 3 == 0:
    continue
  print(i,end=" ")

In [ ]:
for i in range(10,0,-1):
  print(i)

In [ ]:
i = 5
while True:
  print(i)
  i -= 1
  if i < 0:
    break

# List

## List Basics

In [ ]:
# array - homogeneous structure
# list - heterogeneous structure
lst = list()
print(type(lst))
lst = [10,20,30,40,60]
print(len(lst))
print(lst[0])
print(lst[-2])

In [ ]:
marks = []
marks.append(78)
print(marks)

In [ ]:
marks.append(80) # adds an element at the end of the list
print(marks)
marks.insert(1,'AI') # adds an element at the specified position
print(marks)
# marks.pop() # removes an element from the end of the list
marks.pop(1) # removes an element from the specified position
print(marks)
marks.remove(80) # removes an element from the list if it exists
print(marks.index(78))

In [ ]:
# searching
target = 80
if target in marks:
  marks.remove(target)
print(marks)

## List comprehension method

In [ ]:
squared = [i**2+3 for i in range(1,11) if i % 2 == 1]
print(squared)

In [ ]:
lst = [10,20,30,40,60,100,200]
#Iteration: index-based
for i in range(len(lst)):
  print(lst[i])

# Iteration: element-based
for i in lst:
  print(i)

## List Slicing

In [ ]:
squared = [i**2 for i in range(1,11)]
print(squared)
first = []
for i in range(0,5):
  first.append(squared[i])
print(first)
odd_squared = squared[::2]
print(odd_squared)
even_squared = squared[1::2]
print(even_squared)
ind = len(squared)//2
middle = squared[ind:ind+3]
print(middle)

In [ ]:
# List reverse
squared = squared[7:2:-1]
print(squared)

## List Copy

In [ ]:
lst1 = [10,20,30,'AI Lab','Vacation']
print(lst1)
lst2 = lst1
print(lst2)
lst2.append(100)
print(lst1, lst2)

In [ ]:
lst3 = lst1.copy()
lst3.pop()
print(lst1, lst2, lst3)

In [ ]:
# mutable - list, string, dictionary
# immutable - int, float, tuple
a = 'AI Lav at very'
print(a)
print(a+'b')
print(a.index('v'))
a = a.replace('v','b')
print(a)

In [ ]:
lst1.append([20,30,40])
print(lst1)
lst2 = lst1.copy() # shallow copy
print(lst2)
lst2.remove(100)
print(lst1, lst2)
print(lst2[-1][0])
# lst2[-1].pop()
# print(lst2)
# print(lst1)

In [ ]:
import copy
lst3 = copy.deepcopy(lst1) # deepcopy
# print(lst3)
# lst2[-1].pop()
lst3[-1].pop(1)
print(lst1)
print(lst2)
print(lst3)

# Tuple

In [ ]:
a = (1,2,3,4)
print(type(a))
print(a[0])
# a[1] = 5
temp = (32, 33, 35, 36, 34)
print(temp)
coordinate = (0,0)
adjacency_list = ('A',5),('B',6),('C',4)
print(type(adjacency_list))
print(adjacency_list[1][1])

# Dictionary

## Basics

In [ ]:
# Key-Value pairs
# Hashmap - (key,Value)
# Dictionary - Key:Value
# Keys must either be string or integer
s = 'our class will be held online from today' # (i,2), (o,3)
course = {
    'code':'CSE 3812',
    'name':'AI LAB',
    'credit hour':1,
    'duration':2.5,
    'grades':['A','A-','B'],
    827:'Class room',
    3.5: 'Avg'
}
print(type(course))
print(course)

## Indexing

In [ ]:
print(course['grades'])
print(course.get('name'))

## Iteration

In [ ]:
# course['student_grades']
print(course.keys()) # shows all the keys present in the dictionary
print(course.values()) # shows all the values present in the dictionary
print(course.items()) # shows all the key,value pairs in the dictionary

In [ ]:
# Iteration: Key-based
# for i in course.keys():
  # print(course.get(i))
  # print(i, course[i])

# Iteration: Value-based
# for i in course.values():
#   print(i)

# Iteration: Item-based
for i,j in course.items():
  print(i, j)

In [ ]:
course[3.5] = 'Avg cgpa'
course

# Numpy Library

In [ ]:
lst1 = [1,2,3]
lst2 = [4,5,6]
print(lst1+lst2)
print(lst1 * 3)

In [ ]:
import numpy as np
arr1 = np.array(lst1)
print(type(arr1))
arr2 = np.array(lst2)
print(arr1 + arr2)
print(arr1 * 3)
print(arr1.shape)

In [ ]:
arr = np.ones((3,4),'int64')
print(arr)
arr = np.zeros((3,3),'int64')
print(arr)
arr = np.eye(3,4,dtype='int64')
print(arr)

In [ ]:
arr2 = np.arange(1,40,step=2,dtype='float32') # generate random numbers within a range
print(arr2)

[ 1.  3.  5.  7.  9. 11. 13. 15. 17. 19. 21. 23. 25. 27. 29. 31. 33. 35.
 37. 39.]


In [ ]:
arr2 = np.arange(0,1,step=0.01,dtype='float32')
print(arr2)

[0.         0.01       0.02       0.03       0.04       0.05
 0.06       0.07       0.08       0.09       0.09999999 0.11
 0.12       0.13       0.14       0.14999999 0.16       0.17
 0.17999999 0.19       0.19999999 0.21       0.22       0.22999999
 0.24       0.25       0.26       0.26999998 0.28       0.29
 0.29999998 0.31       0.32       0.32999998 0.34       0.35
 0.35999998 0.37       0.38       0.39       0.39999998 0.41
 0.42       0.42999998 0.44       0.45       0.45999998 0.47
 0.48       0.48999998 0.5        0.51       0.52       0.53
 0.53999996 0.55       0.56       0.57       0.58       0.59
 0.59999996 0.61       0.62       0.63       0.64       0.65
 0.65999997 0.66999996 0.68       0.69       0.7        0.71
 0.71999997 0.72999996 0.74       0.75       0.76       0.77
 0.78       0.78999996 0.79999995 0.81       0.82       0.83
 0.84       0.84999996 0.85999995 0.87       0.88       0.89
 0.9        0.90999997 0.91999996 0.93       0.94       0.95
 0.96       0.9699

In [ ]:
arr2 = np.linspace(0,10,50) # evenly-spaced
print(arr2)

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


In [ ]:
arr = np.random.rand(2,2) # generates float numbers
print(arr)
arr = np.random.randint(0,10,(2,3))
print(arr)

[[0.66529019 0.75280157]
 [0.7676128  0.91400392]]
[[6 2 4]
 [7 4 3]]
