In [ ]:
# Problem-1

list=[5,12,7,3,18,9]
list.append(15)
list.insert(2,20)
list.remove(7)
list.sort(reverse=True)
print(list)

[20, 18, 15, 12, 9, 5, 3]


In [ ]:
# Problem-2

numbers=[2,4,6,8,10,12,14,16]
four=numbers[0:4]
print(four)
last=numbers[7:4:-1]
print(last)
print(numbers[2:5])
print(numbers[::-1])
print(numbers[1:8:2])



[2, 4, 6, 8]
[16, 14, 12]
[6, 8, 10]
[16, 14, 12, 10, 8, 6, 4, 2]
[4, 8, 12, 16]


In [37]:
# Problem-3

scores=[55,78,62,49,85,91,73]

great=[scores[i] for i in range(len(scores)) if scores[i]>70]

print(great)

#3
avg=sum(scores)/len(scores)
print(avg)

#4
print(min(scores))
print(max(scores))



[78, 85, 91, 73]
70.42857142857143
49
91


In [44]:
# Problem-4

languages=('C','C++','Java','Python','HTML')
print(languages[0])
print(languages[-1])

valid=[languages[i] for i in range(len(languages)) if languages[i]=='Python']
print(valid)


C
HTML
['Python']


In [45]:
# Problem -5 

student=('Alice',21,'Computer Science',3.75)

name,age,major,gpa=student
print(name)
print(age)
print(major)
print(gpa)

print(f"{name} is {age} years old, studies {major}, and his gpa is {gpa}.")

Alice
21
Computer Science
3.75
Alice is 21 years old, studies Computer Science, and his gpa is 3.75.


In [ ]:
# Problem -6

personal={
    'name':'Alice',
    'age': 23,
    'department': 'cse',
    'cgpa': 3.7
}

print(personal.keys())
print(personal.values())
personal['cgpa']=3.2
print(personal)
personal['university']='UIU'
print(personal)


dict_keys(['name', 'age', 'department', 'cgpa'])
dict_values(['Alice', 23, 'cse', 3.7])
{'name': 'Alice', 'age': 23, 'department': 'cse', 'cgpa': 3.2}
{'name': 'Alice', 'age': 23, 'department': 'cse', 'cgpa': 3.2, 'university': ''}


In [62]:
# Problem -7 

marks= {
    'Math':85,
    'Physics':78,
    'Chemistry':82,
    'Biology':74
}

print(marks.keys())
print(marks.values())

maximum=max(marks, key=marks.get)
print(maximum)

minimum=min(marks, key=marks.get)
print(minimum)

avg=sum(marks.values())/len(marks)
print(avg)


dict_keys(['Math', 'Physics', 'Chemistry', 'Biology'])
dict_values([85, 78, 82, 74])
Math
Biology
79.75


In [65]:
# Problem - 8

products={
    'Laptop':1200,
    'Phone':800,
    'Tablet':450,
    'monitor':300,
    'keyboard':100
}

new_products={i: products[i] for i in products if products[i]>500}

print(new_products)

{'Laptop': 1200, 'Phone': 800}


In [69]:
#Problem - 9
import numpy as np

lst1=[10,20,30,40,50]
arr1=np.array(lst1)
print(arr1*2)

print(arr1.mean())
print(arr1.max())

[ 20  40  60  80 100]
30.0
50


In [ ]:
# Problem -10

import numpy as np

matri = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(matri)

print(matri[1])

print(matri[:,2])

print(matri.sum()) # total sum

print(sum(matri))  #column wise sum

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4 5 6]
[3 6 9]
45
[12 15 18]


In [113]:
# Problem - 11
import numpy as np

arr=np.array([5,12,7,20,3,15,8])

print(arr)

greater=np.array([(arr[i]) for i in range(len(arr)) if arr[i]>10], dtype="int64")
print(greater)

less=np.array([(arr[i]) if arr[i]>10 else 0 for i in range(len(arr))], dtype="int64")
print(less)




[ 5 12  7 20  3 15  8]
[12 20 15]
[ 0 12  0 20  0 15  0]


In [ ]:
#Problem - 12

students=[('Alice',85),('Bob',72),('Charlie',90),('David',65),('Eva',88)]
print(students)

#convert to dictionary
stu_dict=dict(students)
print(stu_dict)

#create a list above 80

above80=[name for name, marks in stu_dict.items() if marks>80]
print(above80)  #list comprehension suru er part e decide kore output ki hobe...

import numpy as np
marks=list(stu_dict.values())
average=np.mean(marks)
print(average)


[('Alice', 85), ('Bob', 72), ('Charlie', 90), ('David', 65), ('Eva', 88)]
{'Alice': 85, 'Bob': 72, 'Charlie': 90, 'David': 65, 'Eva': 88}
['Alice', 'Charlie', 'Eva']


NameError: name 'lst' is not defined

In [ ]:
# Problem - 13
inventory={
    'apple':[10,1.5],
    'banana':[25,0.8],
    'orange':[15,1.2],
    'mango':[8,2.0]
}

total_value={ item: qty*price for item, (qty,price) in inventory.items()}
print(total_value)

import numpy as np
average=list(total_value.values())
mean=np.mean(average)
print(average)


{16.0, 18.0, 20.0, 15.0}


TypeError: unsupported operand type(s) for /: 'set' and 'int'

In [ ]:
# Problem - 14
temps=[22,24,19,23,25,18,21]

import numpy as np
arr=np.array(temps)

mean=np.mean(arr)
max=np.max(arr)
min=np.min(arr)

print(mean)
print(max)
print(min)


dict={
    'mean':mean,
    'max': max,
    'min':min
}
print(dict)

temp_tuple=(max,min)
print(temp_tuple)

TypeError: list indices must be integers or slices, not list

In [ ]:
# Problem - 15

courses={
    'Alice':[85,90,78],
    'Bob': [70,75,80],
    'Charlie': [92,88,95]
}

import numpy as np

avg_dict={}

for name,marks in courses.items():
    avg=np.mean(marks)
    avg_dict[name]=avg

print(avg_dict)


# greater than 85

great85=[name for name, avg in avg_dict.items() if avg>85]
print(great85)

# top students and their score

top_student=max(avg_dict, key=avg_dict.get)
top_tuple=(top_student,avg_dict[top_student])

print(top_tuple)


## CT Question

In [ ]:
# 1 
employees=[
    ('John',[5000,5200,5100]),
    ('Sara',[6000,6100,6200]),
    ('Mike', [4500,4700,4800])
]
emp_dict=dict(employees)
print(emp_dict)

import numpy as np


for salary in emp_dict:
    emp_dict[salary]=np.array(emp_dict[salary])

print(emp_dict)

## average salary
salary_avg={}

for salary in emp_dict:
    salary_avg[salary]=np.mean(emp_dict[salary])
print(salary_avg)

great5500=[name for
 name, avg in salary_avg.items() if avg>5500 ]
print(great5500)


print(emp_dict)


emp_dict2 = emp_dict.copy()
for x in emp_dict2.keys():
    emp_dict2[x] = np.average(np.array(emp_dict2[x]))



emp_dict2 = dict(sorted(emp_dict2.items(), key = lambda x: x[1]  ,reverse=True))

emp_dict2 = emp_dict.copy()
for x in emp_dict2.keys():
    emp_dict2[x] = np.average(np.array(emp_dict2[x]))



emp_dict2 = dict(sorted(emp_dict2.items(), key = lambda x: x[1]  ,reverse=True))

emp_dict2

rank ={}
for x, i in enumerate(emp_dict2.keys()):
    rank[i]= x
rank

list_of_tup = []
for x in emp_dict.keys():
    lst = []
    lst.append(x)
    lst.append(np.average(np.array(emp_dict[x])))
    lst.append(rank[x])
    tup = tuple(lst)
    list_of_tup.append(tup)

print(list_of_tup)

{'John': [5000, 5200, 5100], 'Sara': [6000, 6100, 6200], 'Mike': [4500, 4700, 4800]}
{'John': array([5000, 5200, 5100]), 'Sara': array([6000, 6100, 6200]), 'Mike': array([4500, 4700, 4800])}
{'John': np.float64(5100.0), 'Sara': np.float64(6100.0), 'Mike': np.float64(4666.666666666667)}
['Sara']


In [159]:
print(emp_dict)

{'John': array([5000, 5200, 5100]), 'Sara': array([6000, 6100, 6200]), 'Mike': array([4500, 4700, 4800])}


In [171]:
emp_dict2 = emp_dict.copy()
for x in emp_dict2.keys():
    emp_dict2[x] = np.average(np.array(emp_dict2[x]))



emp_dict2 = dict(sorted(emp_dict2.items(), key = lambda x: x[1]  ,reverse=True))

In [172]:
emp_dict2

{'Sara': np.float64(6100.0),
 'John': np.float64(5100.0),
 'Mike': np.float64(4666.666666666667)}

In [174]:
rank ={}
for x, i in enumerate(emp_dict2.keys()):
    rank[i]= x
rank

{'Sara': 0, 'John': 1, 'Mike': 2}

In [176]:
list_of_tup = []
for x in emp_dict.keys():
    lst = []
    lst.append(x)
    lst.append(np.average(np.array(emp_dict[x])))
    lst.append(rank[x])
    tup = tuple(lst)
    list_of_tup.append(tup)

print(list_of_tup)

[('John', np.float64(5100.0), 1), ('Sara', np.float64(6100.0), 0), ('Mike', np.float64(4666.666666666667), 2)]


In [155]:
#2
numbers=[10,25,30,45,50,60,75,80]

new_numbers=[i for i in numbers if i%5==0 and i%10!=0]
print(new_numbers)

half=[i if i<50 else i/2 for  i in numbers]
print(half)

sort=sorted(half, reverse=True)
print(sort)

middle4=numbers[2:6]
print(middle4)

mid=len(numbers)//2
final=numbers[mid-2:mid+2]
print(final)




[25, 45, 75]
[10, 25, 30, 45, 25.0, 30.0, 37.5, 40.0]
[45, 40.0, 37.5, 30, 30.0, 25, 25.0, 10]
[30, 45, 50, 60]
[30, 45, 50, 60]
